### ISSUE TITLE
leap motion version?

### ISSUE THREAD

**Issue by marc-thornton** [microdee/UE4-SpaceMouse#10]
This approach would work great with a leap motion controller / or web cam to capture hand gestures? Imagine if you could record your camera  sequences by making L-shapes with your thumb and fingers to frame up shots? Pinching to grab and rotate?

**Comment by microdee** [comment]
I'd agree but this is totally outside the scope of this plugin, which is control viewport camera with the space mice as they regularly do in other 3D editors.
