### ISSUE TITLE
Viewport picking offset after moving

### ISSUE THREAD

**Issue by KillerGoldFisch** [microdee/UE4-SpaceMouse#13]
I discovered strange behavior:
When i am selecting an object in the editor and move the viewport using the 3D Mouse, the picking of the Gizmo will become offset to the same position on the screen.

Here is a video showcasing it: [YT](https://youtu.be/ibKAdIhIwdc)

The setup is the same like in https://github.com/microdee/UE4-SpaceMouse/issues/12

**Comment by KillerGoldFisch** [comment]
Ok, i noticed following: When i move the viewport using the 3D Mouse, the region where i can pick the Gizmo stays the same position on the screen, but directly after a "jump" (See https://github.com/microdee/UE4-SpaceMouse/issues/12) the position resets and can be picked on the correct position again.

**Comment by microdee** [comment]
this is a known issue, I'll fix it when I have time. Until then if you nudge the camera in a traditional way the hittesting restores.

**Comment by microdee** [comment]
This was a very easy fix actually, you can get precompiled binaries from https://github.com/microdee/UE4-SpaceMouse/releases/latest
