### ISSUE TITLE
No LICENSE.txt file

### ISSUE THREAD

**Issue by nameOfUser0236** [microdee/UE4-SpaceMouse#14]
I am not a lawyer, however, if I am not mistaken, in a project that lacks a license, all rights are reserved by default.
(see the following:)
 [https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license](url)
[https://github.com/github/choosealicense.com/issues/196](url)
[https://choosealicense.com/no-permission/](url)
[https://www.quora.com/What-if-I-dont-include-a-license-in-my-public-GitHub-project-Can-people-do-anything-with-my-code](url)
[https://stackoverflow.com/questions/16933385/can-my-public-github-project-not-be-open-source](url)
In order to rectify this problem, a license file needs to be added to the project (I personally recommend MIT, but any kind will do.) (Keep up the great work.)

**Comment by microdee** [comment]
sorry I apparently forgot that for this project, I usually go for MIT license so I will add that soon. Thanks for the notice!
