### ISSUE TITLE
Tips for compiling for custom UE builds

### ISSUE THREAD

**Issue by DanMcLaughlin** [microdee/UE4-SpaceMouse#15]
Hello, 
    Great work. Just wondering if we could get a few tips from @microdee or the community as to compile and use this for custom UE builds. We're forced into a custom build which is causing incompatibilities with our plugins.

**Comment by microdee** [comment]
Hi! Just clone the repo with recursive submodules somewhere and copy the plugins folder to your project.

**Comment by DanMcLaughlin** [comment]
Oh great, thanks for the tip. What about for custom UE4 builds, is it as simple as doing the same into the Engine/Plugins folder? Will it automagically compile properly with the BuildTool and such do you know?

**Comment by microdee** [comment]
if you want to deploy it into the engine plugins and create a "precompiled release" for your own engine source then you can use the [DeployForVersion.ps1](https://github.com/microdee/UE4-SpaceMouse/blob/master/DeployForVersion.ps1) script. You might need to add your custom engine path to the search paths in [ProjectModule.psm1](https://github.com/microdee/UE4-SpaceMouse/blob/master/ProjectModule.psm1#L56). It will nicely create a ready to deploy 7zip file.

**Comment by brybalicious** [comment]
Does anyone else have a problem where no visual studio .sln files are created when running 'GenerateProjectFiles.bat' or .sh ?? Therefore, I cannot manually compile. Only via opening an unreal .uproject file and trying to build and debug as it builds before opening.
