### ISSUE TITLE
Lost X,Y,Z panning functionality after altering 3dxWare configuration for UE4Editor

### ISSUE THREAD

**Issue by brybalicious** [microdee/UE4-SpaceMouse#16]
Initially a comment on another issue... but I believe it deserves its own.

# Issue
When I tried to disable 'conflicting mappings' mentioned [here](https://github.com/microdee/UE4-SpaceMouse/issues/12) by going into properties on the 3dx Connection Properties, I completely lost panning and translation functionality in UE4Editor. I guess this is because 3dx finally set some particular mappings for UE4Editor which didn't exist?

# To Reproduce
1. Install 3dxware
2. Install UE4-SpaceMouse plugin to Unreal Editor v 4.25.4
3. Activate UE4-SpaceMouse plugin
4. Use SpaceMouse as expected in Unreal Editor
5. Set application-specific properties for SpaceMouse in Unreal Editor
6. Observe the bug (X,Y,Z panning no longer responding)

# Expected Behaviour
Spacemouse should continue to work... especially after reverting 3dxware settings and restarting the Unreal Editor with Spacemouse plugin

# Attempted Fixes
I deleted the file C:\Users\<username>\AppData\Roaming\3Dconnexion\3DxWare\Cfg\UE4Editor.xml and still, panning (x, y and z axes) has not returned. I removed and then reactivated the spacemouse plugin, and still no functionality. Weird, because it all worked when first installed.

# Configuration
Unreal Editor v4.25.4
SpaceMouse plugin: SpaceMouse-1.0.1-UE_4.25.7z
3DxWare64_v10-7-0_r3248

**Comment by KillerGoldFisch** [comment]
I posted my UE4Editor.xml under my original issue here: https://github.com/microdee/UE4-SpaceMouse/issues/12#issuecomment-722551336
Can you try this?

**Comment by KillerGoldFisch** [comment]
You could also check the debug informations. You can activate them under `Editor Preferences` -> `SpaceMouse` -> `HID` -> `Display Debug Information`.

Then you will get something like this when moving around:

![image](https://user-images.githubusercontent.com/1109517/98283789-726e6d00-1fa0-11eb-9ad4-177a91d117ca.png)

Each of the translation and rotation values are represented as a hex signed 16 bit integer. I merked where each of the values are located.

Do you get any data here?

**Comment by brybalicious** [comment]
Thanks. So, this is with my spacemouse pushed forward and to the right, using my current `UE4Editor.xml`. Somehow, it says that I have two spacemice connected...

![image](https://user-images.githubusercontent.com/8712034/98340471-b186d780-200d-11eb-83ee-4cb49dcfccb6.png)

**Comment by brybalicious** [comment]
I opened Unreal Editor with your `UE4Editor.xml` loaded with a fresh restart of 3DxWare but the issue persisted. I believe that while there is some sort of interaction or conflict, there is something that must be happening on the plugin or Unreal Engine side which has now been stored somewhere. Such a bummer... it was working when I first loaded the plugin...

Any further ideas? Logs or config files I could send you?

**Comment by brybalicious** [comment]
Note: I discovered that somehow this interaction between 3DxWare and Unreal Engine (and perhaps the plugin) spontaneously set my camera speed to -9

I noticed, as I realised I could also not navigate with the regular mouse or keyboard controls whenever I opened the level. The issue was resolved after setting it back to a positive number.

However, the root cause for why this happened still remains a mystery...

**Comment by microdee** [comment]
so after setting the camera speed to normal levels again, did translation come back?

**Comment by brybalicious** [comment]
Okay. Yes, translation came back. Will close the issue and wait and see if it ever reoccurs. Thanks!
