### ISSUE TITLE
pull puck fully back or to the right - movement stops

### ISSUE THREAD

**Issue by mrboni** [microdee/UE4-SpaceMouse#28]
When pulling the puck back or fully to the right the movement stops dead.  Using the marketplace plugin in 4.26

edit - same with both the rotation axis too!

**Comment by microdee** [comment]
thanks for reporting, I've made a release just recently (1.1.1), the update has gone live just 2 hours ago in the marketplace, can you also check if the problem persist in the new version? I will test it on my own of course in a moment.
Also can you tell me which device you have? you can also tell me product and vendor ID if you turn on Display Debug Information under HID section of the plugin preferences.

**Comment by microdee** [comment]
Unfortunately I couldn't reproduce it with version 1.1.1 in UE 4.26.1. Also check if your rotation and translation curves are set properly (doesn't go to 0 at X=1) and looks similar to the screenshot attached

![image](https://user-images.githubusercontent.com/1009962/106672870-18863f00-65b1-11eb-9e0f-350da28fefa4.png)

**Comment by mrboni** [comment]
Thanks for getting back to me.  

I updated and still get the issue.  Am using a Spacepilot Pro with UE4.26.0 on a mostly up to date Windows 10.

The curves are at default.


![image](https://user-images.githubusercontent.com/1789428/107155706-c6a73580-6971-11eb-9a86-2a3ec6514673.png)

**Comment by microdee** [comment]
yeah that doesn't sound like it's working as intended, would you have time for a teamviewer session for a closer look with your controller? it smells like I just don't have the correct assignment for the Space Pilot Pro

**Comment by mrboni** [comment]
Sure. Now?

**Comment by microdee** [comment]
For the record: SpacePilot Pro had some issues with the way how I was filtering input for the most-significant packet meant to indicate the movement for a frame. According to our session I found the cause of the issue and released a fix.
