### ISSUE TITLE
Precompiles compiled for incorrect version

### ISSUE THREAD

**Issue by litruv** [microdee/UE4-SpaceMouse#3]
**4.23**, **4.21** compiled for wrong version

**4.22** and **4.24** tested fine

I use all 4 regularly - thanks for the plugin :)

![image](https://user-images.githubusercontent.com/3798007/77934871-6a5c9980-72fc-11ea-9815-75569df6c56d.png)

All 4 are added to engine same way, in /Engine/Plugins/

**Comment by microdee** [comment]
hmmm, can you clone/download the repo and in powershell can you run `.\DeployForVersion.ps1 UE_4.21` in the project folder and see if the output in `__deploy` works?

**Comment by litruv** [comment]
Did run that command with UE_4.21 as argument, same rebuild prompt comes up (does error out on that one too)

**Comment by microdee** [comment]
I found a potential problem with my build scripts, testing out

**Comment by microdee** [comment]
so facepalm-worthy note: my build script used a classic text-book example of how not to use global variables (in this case in powershell) I lifted that code from our project packager script for CI/CD and the engine version was a constant there so it was fine there, here it's a different story.  I will fix a compilation error on 4.21 and then make a new release now hopefully with the proper binaries.

**Comment by microdee** [comment]
try it now: https://github.com/microdee/UE4-SpaceMouse/releases/tag/0.7.2

**Comment by litruv** [comment]
Seems to work ! Closed + thanks for the promptness :)
