### ISSUE TITLE
Static Mesh editor is bonkers

### ISSUE THREAD

**Issue by microdee** [microdee/UE4-SpaceMouse#30]
it's borked.
Original post:
"if you open a single mesh, that particular workspace has severe jitter when orbiting around Y axis again. This jitter is like a self cancelling oscillation, effectively rendering it usless in this workspace."

**Comment by microdee** [comment]
@Hunanbean you can now test if this issue is really fixed in latest release (1.1.3). You can also close this issue when you can confirm the fix.

**Comment by Hunanbean** [comment]
So far, so good. Thanks again!

**Comment by Hunanbean** [comment]
P.s. I am unable to close this issue, perhaps because you are the author
