### ISSUE TITLE
Spacemouse always in RealTime mode (slows editor)

### ISSUE THREAD

**Issue by Nekbeth** [microdee/UE4-SpaceMouse#37]
Hi,

If we disable the "Real Time" check in the editor, your plug-in turns it ON again every time we navigate. This heavily affects performance while working. Please disable it by default and let us change it from the editor only. 

Also the Menu and Fit buttons change camera speed, very annoying. 

Thanks

** Using UE4 4.26.1

**Comment by microdee** [comment]
See my response in the identical discussion thread you created: https://github.com/microdee/UE4-SpaceMouse/discussions/36#discussioncomment-426441

I fixed the realtime behavior now, but the buttons situation is more elaborate, read explanation in that thread. Please also decide where you'd want to continue discussing this.

**Comment by Nekbeth** [comment]
That is great to hear!!, I'll definitely buy the complete product when the fix comes out. We can continue the discussion in the thread you mentioned. 

Thanks

**Comment by microdee** [comment]
Please try https://github.com/microdee/UE4-SpaceMouse/releases/tag/1.1.4 Marketplace release is coming couple days later

**Comment by microdee** [comment]
if the solution in 1.1.4 doesn't satisfy you please reopen this issue
