### ISSUE TITLE
Fails to compile/launch in certain circumstances with plugin active

### ISSUE THREAD

**Issue by Hunanbean** [microdee/UE4-SpaceMouse#5]
fails with the following messages when selecting 
Launch-Desktop:

ProcessResult.StdOut: LogPluginManager: Error: Unable to load plugin 'SpaceMouse'. Aborting.
Log.WriteException: ERROR: Client exited with error code: 1
PackagingResults: Error: Launch failed! Unknown Error

When selecting
File-Package Project-Windows:
It does not fail

**Comment by microdee** [comment]
unfortunately couldn't reproduce this in 4.25 preview. The test project launches correctly (Launch-Desktop), cooking succeeds and packages correctly, without the above mentioned error.  What UE4 version did you use?

**Comment by microdee** [comment]
hmm I caught this problem on my end in a different project when the plugin was in the editor plugins folder, not in the project folder, apparently it still breaks packaging despite I did all I know to prevent that. so hopefully one day I'll have the answer.

**Comment by Hunanbean** [comment]
Version 4.24.3. I will try with 4.25.0 and report back shortly, and yes, i had it in the engines plugin folder, not the project plugin folder, so i will try both routes

**Comment by Hunanbean** [comment]
Sincere apologies for the long delay.
I cannot reproduce this error in 4.25. seems it was limited to 4.23.1
I currently have it in the engines plugin folder of 4.25, with no ill effects
Thank you very much, be well!

**Comment by firebert85** [comment]
Installing SpaceMouse-1.0.1-UE_4.21 into \\Epic Games\UE_4.25\Engine\Plugins, getting this error after two dialogue boxes saying this plugin is meant for 4.21:

![image](https://user-images.githubusercontent.com/3411843/99831790-9e0b5e80-2b2d-11eb-91f4-fc75b46e731d.png)

Unreal Engine v 4.25.4

**Comment by Hunanbean** [comment]
Although this issue is not appearing when i look at github itself, it did
send me an email notification since i opened the original issue, so i will
reply here.
I suggest redownloading and verify that you downloaded 1.0.1 and not a
previous version. I am running this with 4.25.3 with no issues at this
point.
So, i mean, over on the right hand side of the code page in the section
titled "Releases" and not downloading the source code separately. also once
inside unreal, make sure you enable the HIDUE plugin as well as the titled
SpaceMouse plugin.

**Comment by microdee** [comment]
Oh yeah, don't download the source code of the plugin, use the releases, the big DOWNLOAD button in the readme file also points you to the latest release.
