### ISSUE TITLE
4.27 HIDUE module missing

### ISSUE THREAD

**Issue by anscarlett** [microdee/UE4-SpaceMouse#54]
Hey it was bugging me as well, but `"EnableByDefault": true` didn't do anything.

> due to issues with the HIDUE module

what do you mean by that? can you please elaborate those issues on 4.27 (maybe in a separate issue)?

_Originally posted by @microdee in https://github.com/microdee/UE4-SpaceMouse/issues/53#issuecomment-868975111_

**Comment by anscarlett** [comment]
When i start UE4.27, I get the following message
![UE4 27_HIDUE_Error](https://user-images.githubusercontent.com/507909/123943510-225f7300-d994-11eb-8966-0e8e4d145d1c.png)
Clicking the OK button just goes back to the epic games launcher.

I followed the same installation procedure with the 4.26.2, 4.27 and 5.0p2 releases.

**Comment by anscarlett** [comment]
Just tried building from source packages, all seems to work fine.

**Comment by microdee** [comment]
are you experiencing this with pre-built releases? There's one for 4.27 too https://github.com/microdee/UE4-SpaceMouse/releases/tag/1.2.4

**Comment by anscarlett** [comment]
That was what I first tried. the error appears if I enable the plugin.

Downloaded the source package from the 1.2.4 releases page, built it myself and it works (including the Enabledbydefault option, it appears).

Built with VS2019 using the following command if this helps.

`"C:\Program Files\Epic Games\UE_4.27\Engine\Build\BatchFiles\RunUAT.bat" BuildPlugin -Plugin=C:\Users\anscarlett\Downloads\SpaceMouse-Win64-1.2.4.4.27.0-Source/SpaceMouse.uplugin -TargetPlatforms=Win64 -Package=C:\Users\anscarlett\Downloads\SpaceMouse-Win64-1.2.4.4.27.0-Source\build -Rocket -VS2019`

**Comment by microdee** [comment]
yeah I have that automated, maybe I packaged with an earlier preview release of 4.27

**Comment by anscarlett** [comment]
If you want to reupload the prebuilt package, I'll redownload it and test it again

**Comment by microdee** [comment]
I've updated the build for 4.27 Preview 2 https://github.com/microdee/UE4-SpaceMouse/releases/download/1.2.4/SpaceMouse-Win64-1.2.4.4.27.0-Prev2-PreBuilt.zip
