### ISSUE TITLE
Missing HIDUE?

### ISSUE THREAD

**Issue by StrongerThantheBoys** [microdee/UE4-SpaceMouse#56]
After placing the SpaceMouse folder in the UE4 plugins folder, upon launching UE I got an error message: 

"Plugin 'SpaceMouse' failed to load because module 'HIDUE' could not be found. Please ensure the plugin is properly installed, otherwise consider desabling the plugin for this project."

I'm new to installing GITHUB plugins and just starting with UE4, but I use my SpaceMouse constantly with Blender, so I really want to get this set up. I checked the C:\Program Files\Epic Games\UE_4.26\Engine\Plugins\UE4-SpaceMouse-master\Source\HIDUE folder, and found it to be empty.

How to resolve this?

**Comment by microdee** [comment]
use the releases, not the repository http://github.com/microdee/ue4-spacemouse/releases/latest

**Comment by StrongerThantheBoys** [comment]
Okay, thank you!
