### ISSUE TITLE
The 'SpaceMouse' plugin was designed for build 5.0.0. Attempt to load it anyways?

### ISSUE THREAD

**Issue by softyoda** [microdee/UE4-SpaceMouse#58]
![image](https://user-images.githubusercontent.com/13988751/127868846-9899fdd3-bec3-4697-aa8c-787aa6341c27.png)
If i type yes i have this : 
![image](https://user-images.githubusercontent.com/13988751/127868883-6cf57f22-45c9-4c92-a989-3bef3ef9f729.png)

I don't have any ide and i bought the addon after having the same error from last compiled version from the github. 
UE4.26.2

**Comment by softyoda** [comment]
(I updated last version of 3DxWare today (10.7.4.3350) and 3DxWinCore 17.7.4.
18504

The device used is : SpaceMouse Compact (Fx: 4.37 / PID: S4319180577)

**Comment by softyoda** [comment]
My invoice id for support is : A690104467

**Comment by microdee** [comment]
* UE5 was already in releases.
https://github.com/microdee/UE4-SpaceMouse/releases/latest
* This plugin is not using 3DConnexion drivers nor does it depend on 3DxWare, and it's not affiliated with the official plugin from 3DConnexion (TDxUnrealEditor).
  * please consult https://github.com/microdee/UE4-SpaceMouse/blob/master/DISCLAIMER.md about it

All this info is on the front page of the Marketplace product, or on the Github repo.

**Comment by softyoda** [comment]
I've read disclaimer but as you can read, i did NOT found the official add-on, it seems to exist only in your disclaimer, if I search on Google, I only found your disclaimer.

And I'm using ue4.26 to use your add-on, is there a way I can add it to ue4.26 using the epic game store as I purchased it on it ? Or can you tell me what version present on the GitHub is for ue4.26 or ue4.27 ? 
![image](https://user-images.githubusercontent.com/13988751/128011070-b2996249-cf70-43e6-8f06-2bc241998fef.png)
