### ISSUE TITLE
Plugin fails to launch on 4.25

### ISSUE THREAD

**Issue by mikobit** [microdee/UE4-SpaceMouse#6]
SpaceMouse-0.8.1-UE_4.25 (as well as the preview6 version)
fails to launch with UE Version: 4.25.0-13144385+++UE4+Release-4.25
Tried placing in either the Engine/Plugins folder or the Project/Plugins
In the Engine/Plugins the error is:
"_Plugin 'SpaceMouse' failed to load because module 'SpaceMouseReader' could not be found. Please ensure the plugin is properly installed.._."
In the Project/Plugins the error is:
_The following modules are missing or built with a different engine version:
SpaceMouseReader
SpaceMouseRuntime
SpaceMouse_
- It suggests to rebuild them and then fails to compile.
UE fails to start in both scenarios.
I'm on Windows 10.
Thanks!

**Comment by microdee** [comment]
I will make a release tomorrow for the real 4.25 version, before it was only previews

**Comment by mikobit** [comment]
Perfect, thank you!

**Comment by microdee** [comment]
I built latest release (0.8.1) with the stable version of 4.25, it should work now

**Comment by mikobit** [comment]
Works perfect! Thanks a lot, this is so helpful!
