### ISSUE TITLE
Recording in sequencer

### ISSUE THREAD

**Issue by kerinzeebart** [microdee/UE4-SpaceMouse#62]
Hi,
When I try to add the camera to sequencer or take recorder the 3dconnextion does not register any keyframes on camera. Please see video: Any ideas?
https://www.youtube.com/watch?v=3a1LUnM1Ezw

**Comment by kerinzeebart** [comment]
OK Sorry Found the solution :) The camera in take recorder needs to be set to Possessable and it worked.
![obraz](https://user-images.githubusercontent.com/4799087/141167258-089c901f-336f-4e36-ad15-27478097c484.png)

**Comment by microdee** [comment]
glad to hear that, so is this resolved? can I close it?
