### ISSUE TITLE
Speed Controls Not Working on Spacemouse - Can I map to keyboard instead

### ISSUE THREAD

**Issue by agencydhd** [microdee/UE4-SpaceMouse#69]
Hi,

Thanks for creating this. I purchased through the marketplace. I am trying to change the speed so I can get used to navigation but the spacemouse buttons bring up their own shortcuts instead - even after removing the Unreal folder from the 3DConnexion install. If there's no way to correct that, could I map to a keyboard shortcut or control manually instaed?

**Comment by microdee** [comment]
Hi! you can unassign these functionalities in the per-application settings of 3DxWare. This settings are brought up either via the "Menu" button, or if you have a Space Navigator, the Left button by default. Then look for "Buttons" and remove the default assignments of each buttons there. This will be only saved for Unreal Engine. Also while you're there disable scroll wheel emulation as well so your moving/leaning forward/backward won't be jumpy.

Or alternatively if you're not using your SpaceMouse in other software you can just disable the entire 3DxWare service (either via the "Stop 3DxWare" start menu icon, or with the Windows Service manager)

**Comment by microdee** [comment]
OR I've just realized you might refer to the default behavior where the Configuration of the Unreal spacemouse plugin is brought up on pressing the menu button. In that case you can unassign that by selecting "None" or a non-existent button for "Show Space Mouse preferences button" option.
