### ISSUE TITLE
Unable to startup with UE5 Preview 1

### ISSUE THREAD

**Issue by Joseph-DiGiovanni** [microdee/UE4-SpaceMouse#70]
![image](https://user-images.githubusercontent.com/37851452/155563115-e1ead5a7-87a2-456f-80df-743279965bf3.png)
![image](https://user-images.githubusercontent.com/37851452/155563216-05e8ddcf-7a34-49b4-a358-065cfbbaa214.png)

Using SpaceMouse-Win64-1.2.4.5.0.0-PreBuilt.zip on Windows 11, was working fine on 5.0.0 Early Access 2

**Comment by Joseph-DiGiovanni** [comment]
![image](https://user-images.githubusercontent.com/37851452/155652480-1b5ed522-552a-4a3c-9495-9f03ed569cb7.png)
I should add the 3DxWare plugin is not working either, so it seems unreal broke some plugin compatibility with the update rather than something specific to this plugin.

**Comment by aknittel1** [comment]
Same for me. Preview 1 will not open a project that was already using this plug-in. How do we get the developer to address this?

**Comment by aknittel1** [comment]
![image](https://user-images.githubusercontent.com/22087392/156088592-281e4d1d-242c-471c-bcaf-5657ed999d46.png)

**Comment by Joseph-DiGiovanni** [comment]
> ![image](https://user-images.githubusercontent.com/22087392/156088592-281e4d1d-242c-471c-bcaf-5657ed999d46.png)

The plugin from the store will not attempt to install on UE5 as it's not officially supported. You need to use the zip file from the releases page which at the moment only seems to work with UE5 early access

**Comment by aknittel1** [comment]
I contacted the developer, he's fixing the plug-in to be compatible with Preview 1. Yup, I always install it from Microdee Github Prebuilt version.

**Comment by microdee** [comment]
closing this as archive is replaced with a binary compatible with 5.0.0-p2
