### ISSUE TITLE
5.0EA prebuilt release is binary incompatible with 5.0 Preview 1/2

### ISSUE THREAD

**Issue by microdee** [microdee/UE4-SpaceMouse#71]
This is what I get with UE 5 Preview 1:

![image](https://user-images.githubusercontent.com/22087392/156206361-898f83d3-1650-4fb8-87df-af6a1e1180f5.png)

_Originally posted by @aknittel1 in https://github.com/microdee/UE4-SpaceMouse/discussions/51#discussioncomment-2274583_

**Comment by inkoml** [comment]
It doesn't work on ue5 preview2 either

**Comment by microdee** [comment]
yep, that'll be updated shortly. They released the preview 2 update right after I built for preview 1. And yep, each minor patch for Unreal is binary incompatible with the previous one. That's why it would be better if the general public would be more acquainted with compiling source code, I don't need to change a single character in the source to make these new builds.

**Comment by microdee** [comment]
@inkoml https://github.com/microdee/UE4-SpaceMouse/releases/download/1.2.4/SpaceMouse-Win64-1.2.4.5.0.0-PreBuilt.zip this should work for 5.0 Prev2

**Comment by inkoml** [comment]
> 

It works finally !! Big thanks!!! miss my spacemouseT~T !!

**Comment by aknittel1** [comment]
Tested with Preview 2 -- No issues. THanks!
