### ISSUE TITLE
Lock input to editor in focus

### ISSUE THREAD

**Issue by DanMcLaughlin** [microdee/UE4-SpaceMouse#8]
I often run multiple instances of Unreal simultaneously. When doing this the 3D puck controls all instances, not the one in focus. Request to have SpaceMouse only activate when the window is in focus. Thanks for a fantastic plugin otherwise.

**Comment by microdee** [comment]
good point, I will add this when I find time

**Comment by DanMcLaughlin** [comment]
@microdee Ah that would be great. Yeah I'll go off into blender, use the 3dmouse, come back to UE4 and the viewport will be all over the place because it was listening in to what I was doing in blender.

**Comment by microdee** [comment]
please try new release (1.0.0), this feature should be added there
