### ISSUE TITLE
Tilting SpaceMouse tilts *and* zooms in-and-out. How to turn off zoom effect?

### ISSUE THREAD

**Issue by flonase** [microdee/UE4-SpaceMouse#85]
Hello! The only trouble I'm having is with the title above. For example, when I tilt the mouse to look at my object from above, it simultaneously zooms out by some set amount continuously throughout tilt input, resulting in this cumbersome motion of tilt, zoom back in, tilt to destination, zoom back in, etc. etc.

I'm not certain which setting I need to change or how they really interact. I use the mouse for Sketchup and Twinmotion without issue, so this is a first. 

Thank you!

**Comment by microdee** [comment]
please see README.md
![image](https://user-images.githubusercontent.com/1009962/205618349-9a49ec29-299a-452b-8bb1-6c2e9568d19f.png)
https://github.com/microdee/UE4-SpaceMouse#known-issues

disable mouse wheel emulation in 3DxWare driver for Unreal Editor

**Comment by microdee** [comment]
This is now automatically handled and fixed in upcoming 2.0.1 release.
