### ISSUE TITLE
Could not find definition for module 'HIDUE'

### ISSUE THREAD

**Issue by geekrelief** [microdee/UE4-SpaceMouse#87]
I'm compiling from source against the UE5-main branch after including the repo in my project in `Plugins/SpaceMouse`.

I get an error when building from Visual Studio: `Could not find definition for module 'HIDUE', (referenced via default plugins -> SpaceMouse.uplugin)`.

I tried removing the references to it in the uplugin file and in the SpaceMouseReader.Build.cs and recompiled, but rain into more errors in `SpaceMouse\Source\SpaceMouseReader\Private\DebugInfoPrinter.cpp`: missing `hidapi.h` and
`SpaceMouse\Source\SpaceMouseReader\Public\SmUeVersion.h`: missing `Launch/Resources/Version.h`.

**Comment by microdee** [comment]
did you clone my repo recursively? HIDUE is a submodule of this repo. If you didn't use git, also note that the github download feature just silently ignores submodules.

**Comment by microdee** [comment]
This should have been fixed some while ago so closing
