### ISSUE TITLE
Losing axis mappings in Play and Packaging

### ISSUE THREAD

**Issue by benjyvc** [microdee/UE4-SpaceMouse#94]
Warning, a bit of messiness here. With SpaceMouse 1.2.6 loaded in UE 5.0.1 I'm losing axis mappings in Play mode and in packaged game, but all behavior in Editor is expected. In a new game with Starter Content nothing works in Play mode. With 3dX loaded instead, everything works in Play except no up/down movement. For starters, is this expected behavior, if so, what am I missing in setup?

In my project however, I had a coder take over, he (unwittingly?) enabled both 3dXUnreal and SpaceMouse plugins, then added this node structure to the VR_Character to get expected behavior in Play mode, but in the packaged game I lose pitch and yaw: 
![Axis_Mappings](https://github.com/microdee/UE4-SpaceMouse/assets/14839594/ef60e8b8-ab3d-4b3d-a771-8baf0edb4eff)

[Here's a table](https://docs.google.com/spreadsheets/d/1N4qLF6VfWLt8GtbQBYFlVKIxNLaDCnbR3vckWRgU_Mg/edit?usp=sharing) that records the settings and behaviors for both plugins, individually and together. It doesn't show what I just described with both plugins enabled, but yes, what a mess. Many thanks if you can assist.

**Comment by microdee** [comment]
So well I didn't understand any of that, check https://github.com/microdee/UE4-SpaceMouse-TestProject for gameplay implementation.

Both official and this plugin can co-exist however editor navigation is untested with that. For jumping forward and backward please read this issue https://github.com/microdee/UE4-SpaceMouse/issues/85 (TL;DR, disable mousewheel emulation in 3DxWare for unreal).

And of course editor settings about device axis in the Plugin config are not carried into gameplay, you need to program that yourself.

**Comment by benjyvc** [comment]
Hi David,

Sorry to confuse you, but seems your response reflects you got most of it. I’ll check out the link. Glad to hear both plugins can co-exist, now just a matter of gameplay implementation.

Best,
Benjy



￼

www.photo2topo.com

••••••••••••••••••••••••••••••
Benjamin von Cramon - Founder

mobile 678.283.2557

2266 Old Sewell Road
Marietta, GA  30068-3451
