### ISSUE TITLE
Compat. with 5.3 - When?

### ISSUE THREAD

**Issue by aknittel1** [microdee/UE4-SpaceMouse#95]
Sorry for asking since 5.3 was just released today. I want to avoid my extra effort to rebuild this myself.

**Comment by microdee** [comment]
When it's done™
In the future I will automatically close questions like this, because these are not making releases faster, these are not an actual bug or feature request and I've yet to see a serious studio using 0-day engine releases.

**Comment by aknittel1** [comment]
:) Understood.
